package com.example.simple_survey_tool.model_layer;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;


/**
 * An entity class represents a table in a relational database
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name = "surveys")
public class Survey {
    public Survey(UUID surveyId) {
        this.id = surveyId;
    }
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;
    @OneToMany(mappedBy = "survey_id",  orphanRemoval = true) // cannot use 'cascade = CascadeType.ALL' here. The survey id is generated by the db and hence null, when autogenerated by java.
    private List<Question> questions;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private Integer response_count;
    private String description;
}